
version: 2

models:
  - name: read_bigquery_data
    description: "Reads data from BigQuery"

  - name: data_pipeline
    description: "Creates a Feature Group populated with data from BigQuery table"

  - name: schedule_pipeline
    description: "Parses todays data and inserts into existing feature group"
 

