
version: 2

models:
  - name: read_bigquery_data
    description: "Reads data from BigQuery"

  - name: feature_group_creation
    description: "Create an Online Feature Group"

  - name: data_pipeline
    description: "Parse Data"

  - name: fg_insert
    description: "Insert parsed data into Online Feature Group"

  - name: big_query_insert
    description: "Insert parsed data into BigQuery"
 

