USERS_AMOUNT_HISTORICAL = 100_000
VIDEO_AMOUNT_HISTORICAL = 100_000
INTERACTIONS_AMOUNT_HISTORICAL = 2000_000

USERS_AMOUNT_PIPELINE = 1_000
VIDEO_AMOUNT_PIPELINE = 1_000
INTERACTIONS_AMOUNT_PIPELINE = 10_000

DATE_TIME_FORMAT = '%Y-%m-%d %H:%M:%S'
DAY_FORMAT = '%Y-%m-%d'
MONTH_FORMAT = '%Y-%m'

KAFKA_TOPIC_NAME = "interactions_streaming_test_trial1"
SCHEMA_NAME = "interactions_streaming_test_trial_schema1"
